# Generated by Django 4.1.7 on 2023-05-09 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_alter_enrollment_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
