# Generated by Django 4.1.7 on 2023-05-09 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='time_stamp',
        ),
    ]
